### PR TITLE
Implement a New Public Function to Revert a Patch

### LINKED ISSUE #1: Ability to unregister and reload patches
Hi
Would it be possible to add an unregister_extensions() function? Or have the register_extensions function do a reload() of the packages passed into it? I think it would speed up developing with gorilla and help with troubleshooting
Thanks for the awesome module
Luke

### PR DESCRIPTION
**Pull request by christophercrouzet**
Resolves #1.

### CODE REVIEW

**Comment by jayvdb** [comment]
For my own use cases, it would be helpful to have some test cases which ensure that nested use of patch/review behave in a predictable manner.  I usually dont care what that default behaviour is, as long as it is predictable, so it is consistent between releases and any enhancements to introduce different nested behaviours require explicit opt-in so-as to not break the default.

But just adding revert without any guarantees for nested invocation is a great improvement, and will help many use cases where a context manager in a single threaded app needs to inject code before a specific chunk of code and immediately remove it.

**Comment by christophercrouzet** [comment]
Hello @jayvdb!

Just to make sure that I'm understanding this correctly—when you mentioned ‘nested’, are you referring to the process of applying patches on top of attributes that were already patched?

**Comment by jayvdb** [comment]
yup.  with alternative patches, typically two context decorators where one undoes the other temporarily.  e.g. `test_nested_readonly_enabled` in https://github.com/christophercrouzet/gorilla/pull/4

**Comment by christophercrouzet** [comment]
I see, thanks!

It should be straightforward to store a FILO (first-in, last-out) stack of the patches applied to allow reverting them correctly, however I'm unsure how the [gorilla.get_original_attribute()](https://gorilla.readthedocs.io/en/latest/utilities.html#gorilla.get_original_attribute) would work in that case—e.g., how to ensure that a function used as the 2nd patch can access the expected original function and not one from another entry from the stack, if that makes sense?

It's probably doable somehow but I'd need to give it some proper thoughts.

**Comment by jayvdb** [comment]
Yes, this is a similar problem as `functools.wrap`, which needs to allow discovery of the original function.  It does this by allowing traversal through an attribute on each wrapper, and if all wrapping follows the protocol then the chain to the original can be followed.

For my own purposes, context managers, the behaviour of `get_original_attribute()` and similar could be documented as undetermined when multiple patches are applied to the same original, or even better be an exception, if you can not find an easy solution for it.  This is because the typical use of context managers is that the context manager is not concerned with it the scope it is in (be it patched or unpatched), and code inside the context being managed is unaware that it is operating in a patched environment.

**Comment by christophercrouzet** [comment]
Alrighty! I added support for applying stacks of patches, let me know if that works for you!

I also preserved the intended behaviour of `get_original_attribute()` by adding an optional `id` parameter to it, so it's still possible to retrieve a specific original attribute from the stack.

**Comment by jayvdb** [comment]
ok, I'll give it spin shortly and report back

**Comment by jayvdb** [comment]
I did a local-only rebuild of https://github.com/streeter/django-db-readonly/pull/22/files using gorilla with this PR, and it worked perfectly.

**Comment by christophercrouzet** [comment]
Awesome, thanks @jayvdb, glad that it works out! :) I'll be merging this branch then.

**Pull request merged**
